// +build ignore

// This program generates emojis.go. It can be invoked by running
// go run gen.go
package main

import (
	"fmt"
	"html/template"
	"os"
	"strings"
	"time"
)

func main() {
	user := os.Getenv("USER")
	if user == "" {
		user = "robots"
	}
	v1Lines := getLines("emojisV1.txt")
	v2Lines := getLines("emojisV2.txt")
	doc := document{
		User:      user,
		Timestamp: time.Now().Format(time.RFC3339),
		EmojisV1:  v1Lines,
		EmojisV2:  v2Lines,
	}
	ef, err := os.Create("mapping.go")
	handle(err)
	defer ef.Close()
	handle(mappingTemplate.Execute(ef, doc))
}

func getLines(fileName string) []string {
	buf, err := os.ReadFile(fileName)
	handle(err)
	return strings.Split(string(buf), "\n")
}

func handle(err error) {
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

type document struct {
	User      string
	Timestamp string
	EmojisV1  []string
	EmojisV2  []string
}

var mappingTemplate = template.Must(template.New("").Parse(`// Code generated; DO NOT EDIT.
// This file was generated by {{ .User }} at
// {{ .Timestamp }}
package ecoji


// padding at position 0 is output when 3 or less input bytes are present
// padding at possitions 1 to 4 are sued when only 4 of 5 input bytes are presetn

var paddingV1 = [5]rune{0x2615,0x269C,0x1F3CD,0x1F4D1,0x1F64B}
var paddingV2 = [5]rune{0x2615,0x1FAB4,0x1F6FC,0x1F4D1,0x1F64B}

var emojisV1 = [1024]rune{
{{- range $i, $emoji := .EmojisV1 }}
	0x{{$emoji}},
{{- end }}
}

var emojisV2 = [1024]rune{
{{- range $i, $emoji := .EmojisV2 }}
	0x{{$emoji}},
{{- end }}
}

var revEmojisV1 = map[rune]int{
{{- range $i, $emoji := .EmojisV1 }}
	0x{{$emoji}}: {{$i}},
{{- end }}
}

var revEmojisV2 = map[rune]int{
{{- range $i, $emoji := .EmojisV2 }}
	0x{{$emoji}}: {{$i}},
{{- end }}
}

`))
